# Generated by Django 5.0.3 on 2024-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='contactno',
            field=models.CharField(default='hi', max_length=10),
            preserve_default=False,
        ),
    ]
